name: test_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.2
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  auto_route: ^5.0.1
  dartz: ^0.10.1
  lottie: ^1.4.3
  flutter_native_splash: ^2.2.13
  flutter_launcher_icons: ^0.10.0
  validators: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.0
  json_serializable: ^6.3.2
  injectable_generator: ^1.5.4

flutter:
  assets:
    - assets/animations/
    - assets/images/
  uses-material-design: true

